#!/bin/bash

### BEGIN INIT INFO
# Provides: cj-unattended-upgrades
# Required-Start: $local_fs $network
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: cj's unattended apt upgrades
# Description: see https://github.com/pflanze/cj-unattended-upgrades
### END INIT INFO

set -euo pipefail
IFS=

mypath=$(readlink -f "$0")
myname=$(basename "$mypath")
mydir=$(dirname "$mypath")
# Verify sanity of installation:
# - get config, including setting PATH
source "$mydir/shared.sh"
# - check for dependencies (chj-scripts, and Time::ParseDate)
_version=$(pmversion -p Time::ParseDate)

logdir=/var/log/cj-unattended-upgrades

help() {
    echo "$0 start|stop|restart|status"
    exit 1
}

if [ $# -ne 1 ]; then
    help
fi

daemonize --multilog "$logdir" --action "$1" \
          "$mydir"/cj-unattended-upgrades-daemon

# ^ No need to run the daemon script via `loop`?
