#!/bin/bash

set -euo pipefail
IFS=

myname=$(basename "$0")
mydir=$(dirname "$0")
source "$mydir/shared.sh"

dry_or_y=
if [ "${CJ_UNATTENDED_UPGRADES_DRY_RUN-}" = 1 ]; then
    dry_or_y=--dry-run
else
    dry_or_y=-y
fi

updatetmp=
upgradetmp=

perhaps_showfile () {
    local filekind
    local perhaps_filepath
    filekind="$1"
    perhaps_filepath="$2"
    if [ -n "$perhaps_filepath" ]; then
        echo "/==== $filekind: ============================================\\"
        cat "$perhaps_filepath"
        echo "\\============================================================/"
        echo
    fi
}

die () {
    echo "Subject: $myname failure: $*"
    echo
    perhaps_showfile "update output" "$updatetmp"
    perhaps_showfile "upgrade output" "$upgradetmp"
    rm -f "$spoolfile"
    exit 0 # OK?
}

date > "$spoolfile"

updatetmp=$(mktemp)

# apt-get -q=2 update > "$updtmp" 2>&1
apt-get update \
        > "$updatetmp" 2>&1 || die "apt-get update failed"

upgradetmp=$(mktemp)

export DEBIAN_FRONTEND=noninteractive
apt-get dist-upgrade "$dry_or_y" -o Dpkg::Options::="--force-confold" \
        > "$upgradetmp" 2>&1 || die "apt-get dist-upgrade failed"

# Were there upgrades?  If so, say so.  Otherwise, say nothing.

numdone=$(tail -1 "$upgradetmp" | perl -wne '
    $z = 0;
    if (my ($n) = /\b(\d+) upgraded/) { $z += $n } 
        else { warn "no match: upgraded" }
    if (my ($n) = /\b(\d+) newly installed/) { $z += $n }
        else { warn "no match: newly installed" }
    print $z or die $!
')

if [ "$numdone" -gt 0 ]; then
    echo "Subject: $myname: $numdone packages upgraded/installed"
    echo
    perhaps_showfile "update output" "$updatetmp"
    perhaps_showfile "upgrade output" "$upgradetmp"
fi

rm -f "$updatetmp" "$upgradetmp"
rm -f "$spoolfile"
